name: test if lint works

on:
  push:
    branches: [ "add-price-list-module" ]
  pull_request:
    branches: [ "add-price-list-module" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run lint